language: php
php:
- '7.2'
cache:
  directories:
  - "$HOME/.composer/cache/files"
before_install:
- composer global require hirak/prestissimo
before_script:
- composer install
script:
- vendor/bin/phpunit tests/InjectProccessorTest.php
