language: php
php:
- '7.2'
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.composer/cache/files"
before_install:
- composer global require hirak/prestissimo
before_script:
- composer install
script:
- vendor/bin/phpunit ./tests
